version: '2'

services:
  zk:
    image: jplock/zookeeper:3.5.2-alpha
    ports:
      - 2181:2181

  fan:
    build: drf_sample
    command: ./run.sh
    depends_on:
      - zk
    volumes:
      - ../fan:/fan
    environment:
      - ZK_HOST=zk
