version: '2'

services:
  zk:
    image: jplock/zookeeper:3.5.2-alpha
    ports:
      - 2181:2181

  fan:
    build: drf_sample
    command: ./run.sh
    depends_on:
      - zk
    volumes:
      - ../fan:/fan
      - ../../tipsi_tools:/tipsi_tools
      - ./drf_sample:/code
    environment:
      - ZK_HOST=zk
      - ZIPKIN=zipkin:9411
      - PYTHONPATH=/fan:/tipsi_tools

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
